### PR TITLE
BUG: renamed DICOM TAG from DCM_OtherPatientIDs to DCM_RETIRED_OtherP…

### LINKED ISSUE #7: PETDICOMExtension is not available in Slicer ExtensionManager
see http://slicer.cdash.org/viewBuildError.php?buildid=1066505 for further information

Cause by most recent DCMTK update which set DCM_OtherPatientIDs to retired

### PR DESCRIPTION
**Pull request by che85**
…atientIDs (issue #7)

fixes #7

### CODE REVIEW

File: SUVFactorCalculatorCLI/dcmHelpersCommon.cxx [hunk 1]
```diff
@@ -20,7 +20,7 @@ const DcmTagKey dcmHelpersCommon::patientModuleTags[] = {
   DCM_QualityControlSubject,
   DCM_PatientBirthTime,
   DCM_ReferencedPatientSequence,
-  DCM_OtherPatientIDs,
+  DCM_RETIRED_OtherPatientIDs,
```
Comment (fedorov) [inline SUVFactorCalculatorCLI/dcmHelpersCommon.cxx]: Let's just remove this attribute from the list. See note in http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.2.2.html.

**Review by fedorov — CHANGES_REQUESTED** [review]

**Review by fedorov — APPROVED** [review]
